include:
  - board: xiao_ble//zmk
    shield: Pyuron_R rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: xiao_ble//zmk
    shield: Pyuron_L rgbled_adapter
  - board: xiao_ble//zmk
    shield: settings_reset
 
